<!-- Page-Title -->
<div class="row">
    <div class="col-sm-12">
        <h4 class="page-title">
            Process swap request
        </h4>
    </div>
</div>

<form method="post" action="/swaps/save/<?=$swap->id?>">

<div class="row">

    <div class="col-xs-12 col-lg-12">

            <div class="row">
                <div class="col-lg-12 col-sm-12 col-xs-12 col-md-12 col-xl-6">
                    <div class="card-box">
                        <h4 class="header-title m-t-0 m-b-30">Swap info</h4>

                        <div class="form-group row">
                            <div class="col-sm-3"><strong>New address</strong></div>
                            <div class="col-sm-9">
                                <?php echo $swap->new_address ?>
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-sm-3"><strong>Immediate address</strong></div>
                            <div class="col-sm-9">
                                <?php echo $swap->immediate_address ?>
                            </div>
                        </div>

                        <div class="form-group row">
                            <div class="col-sm-12"><strong>Immediate address balance</strong></div>
                            <div class="col-sm-12">
                                <?php
                                    if(is_object($balance)){
                                        echo ucfirst($balance->error).' Coins not deposited yet!';
                                    }
                                    else
                                    {
                                        echo $balance;
                                    }
                                ?>
                            </div>
                        </div>

                        <div class="form-group row">
                            <div class="col-sm-3"><strong>Notify user</strong></div>
                            <div class="col-sm-9">
                                <?php echo $swap->notify_address ? $swap->notify_address : '-' ?>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-lg-12 col-sm-12 col-xs-12 col-md-12 col-xl-6 m-t-sm-40">
                    <div class="card-box">
                        <h4 class="header-title m-t-0 m-b-30">Process swap</h4>

                        <div class="form-group row">
                            <label class="col-sm-3">Coins are swapped</label>
                            <div class="col-sm-9">
                                <div class="checkbox checkbox-primary">
                                    <input type="hidden" name="swapped" value="0">
                                    <input id="active"  name="swapped" type="checkbox" value="1" <?=$swap->swapped == 1 ? 'checked' : ''?>>
                                    <label for="active">
                                        I'm sure the coins are swapped
                                    </label>
                                </div>
                            </div>
                        </div>

                    </div>

                    <button type="submit" class="btn btn-primary">Save swap</button>
                    <a href="/admins" class="btn btn-secondary">Cancel</a>

                </div>




            </div>


        </div>
    </div><!-- end col-->

</form>


</div>
<!-- end row -->
