<!-- Page-Title -->
<div class="row">
    <div class="col-sm-12">
        <h4 class="page-title">Administrator bewerken</h4>
    </div>
</div>

<form method="post" action="/admins/save/<?=$admin->id?>">

<div class="row">

    <div class="col-xs-12 col-lg-12">

            <div class="row">
                <div class="col-lg-12 col-sm-12 col-xs-12 col-md-12 col-xl-6">
                    <div class="card-box">
                        <h4 class="header-title m-t-0 m-b-30">Default info</h4>

                        <div class="form-group row">
                            <label for="name" class="col-sm-2 form-control-label">Name</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" name="name" id="name" placeholder="Name" value="<?=$admin->name?>">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="username" class="col-sm-2 form-control-label">Username</label>
                            <div class="col-sm-10">
                                <input type="username" class="form-control" name="username" id="username" placeholder="Username" value="<?=$admin->username?>">
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-lg-12 col-sm-12 col-xs-12 col-md-12 col-xl-6 m-t-sm-40">
                    <div class="card-box">
                        <h4 class="header-title m-t-0 m-b-30">Login info</h4>

                        <div class="form-group row">
                            <label for="password" class="col-sm-2 form-control-label">Password</label>
                            <div class="col-sm-10">
                                <input type="password" class="form-control" id="password" placeholder="Password" name="password" autocomplete="new-password" value="">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-sm-2">Login</label>
                            <div class="col-sm-10">
                                <div class="checkbox checkbox-primary">
                                    <input type="hidden" name="active" value="0">
                                    <input id="active"  name="active" type="checkbox" value="1" checked="<?=$admin->active?>">
                                    <label for="active">
                                        Able to login
                                    </label>
                                </div>
                            </div>
                        </div>

                    </div>

                    <button type="submit" class="btn btn-primary">Save administrator</button>
                    <a href="/admins" class="btn btn-secondary">Cancel</a>

                </div>




            </div>


        </div>
    </div><!-- end col-->

</form>


</div>
<!-- end row -->

<?=$this->assets->outputJs('dealers_js')?>