<?=date_default_timezone_set ( 'Europe/Amsterdam' );?>
<!doctype html>
<html>
<head>
    <meta charset="utf-8">

    <style>
        @page{
            background-image: url("./files/pdf_background/voting_report.png");
            background-image-resize: 6;
            margin: 210px 30px 130px 65px;
        }
        body{
            font-family: gillsans;
        }
    </style>
</head>

<body>

    //Todo
    Voting Report Content

</body>
</html>