
<div>
    <div class="row">
        <div class="col-sm-12">
            <div class="btn-group pull-right m-t-15">

                <button type="button" class="btn btn-custom dropdown-toggle waves-effect waves-light" data-toggle="dropdown" aria-expanded="false">Actions</button>

                <div class="dropdown-menu">
                    <a class="dropdown-item" href="/votings/report/<?=$voting->id?>" target="_blank">Create report</a>
                </div>

            </div>
            
            <h4 class="page-title">Votes in voting <em>"<?=$voting->title?>"</em></h4>
        </div>
    </div>

    <div class="row">

        <div class="col-xs-12 col-lg-12">
            <div class="card-box">

                <?php if(!$wallet_status){ ?>
                    <div class="alert alert-danger" role="alert">
                        Can't connect to the EUNO wallet. Please validate the signed messages manually!
                    </div>
                <?php } ?>

                <div class="table-responsive">
                    <table id="datatable" class="table table-striped table-bordered m-b-0">
                        <thead>
                        <tr>
                            <th>
                                IP address + port
                            </th>
                            <th>Collateral address</th>
                            <th>Answer</th>
                            <th>Signed message</th>
                            <th>Vote date</th>
                            <th>Signed message check</th>
                            <th>Vote confirmed</th>
                            <th></th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php foreach( $votes as $v ){ ?>
                            <tr>
                                <td><?=$v->masternode_ipaddress_port?></td>
                                <td><?=$v->masternode_address?></td>
                                <td><?=$v->answer?></td>
                                <td>
                                    <a href="javascript:void(0)" class="openSignedMessageModal" data-msg="<?=$v->signed_msg?>">View signed message</a>
                                </td>
                                <td><?=date("Y/m/d H:i:s", $v->date)?></td>
                                <td>
                                    <?php
                                    if($v->checkHash() !== 'error'){ ?>
                                        <span class="label label-success" title="Signed message valid">
                                            <i class="fa fa-check"></i>
                                        </span>
                                    <?php }else{ ?>
                                        <span class="label label-danger" title="Signed message invalid">
                                            <i class="fa fa-times"></i>
                                        </span>
                                    <?php } ?>
                                </td>
                                <td>
                                    <?php if($v->confirmed == 0){ ?>
                                        <span class="label label-default" title="Vote not judged yet">-</span>
                                    <?php } ?>

                                    <?php if($v->confirmed == 1){ ?>
                                        <span class="label label-success" title="Vote approved">
                                            <i class="fa fa-check"></i>
                                        </span>
                                    <?php } ?>

                                    <?php if($v->confirmed == 2){ ?>
                                        <span class="label label-danger" title="Vote declined">
                                            <i class="fa fa-times"></i>
                                        </span>
                                    <?php } ?>
                                </td>
                                <td>
                                    <?php if($v->confirmed == 0 || $v->confirmed == 2){ ?>
                                    <a href="/votings/approve/<?=$voting->id?>/<?=$v->id?>" class="btn waves-effect waves-light btn-sm btn-success" title="Approve vote"> <i class="fa fa-check"></i> </a>
                                    <?php } ?>

                                    <?php if($v->confirmed == 0 || $v->confirmed == 1){ ?>
                                    <a href="/votings/decline/<?=$voting->id?>/<?=$v->id?>" class="btn waves-effect waves-light btn-sm btn-danger" title="Decline vote"> <i class="fa fa-times"></i> </a>
                                    <?php } ?>
                                </td>
                            </tr>
                        <?php } ?>
                        </tbody>
                    </table>
                </div>

            </div>
        </div><!-- end col-->
    </div>
    <!-- end row -->
</div>

<!-- Modal -->
<div class="modal fade" id="signedMessageModal" tabindex="-1" role="dialog" aria-labelledby="signedMessageModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Signed message</h4>
            </div>
            <div class="modal-body">
                <span class="signedMessageBox"></span>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>


<script type="application/javascript">
    $(function(){
        $('.openSignedMessageModal').each(function(){
            var $btn = $(this);

            $btn.on('click', function(){
                $('#signedMessageModal').modal('show');

                $('.signedMessageBox').text( $(this).data('msg') );
            });
        });
    })
</script>