<!-- Page-Title -->
<div class="row">
    <div class="col-sm-12">
        <h4 class="page-title">
            <?php if($voting->id){ ?>
                Edit proposal
            <?php }else{ ?>
                Add proposal
            <?php } ?>
            <?=($voting->id && $voting->round == 2 ? ' (Second voting round)' : '')?>
        </h4>
    </div>
</div>

<form method="post" action="/votings/save/<?=$voting->id?>">

<div class="row">

    <div class="col-xs-12 col-lg-12">

            <div class="row">
                <div class="col-lg-12 col-sm-12 col-xs-12 col-md-12 col-xl-6">
                    <div class="card-box">
                        <h4 class="header-title m-t-0 m-b-30">Default info</h4>

                        <div class="form-group row">
                            <label for="name" class="col-sm-2 form-control-label">Title</label>
                            <div class="col-sm-10">
                                <input type="title" class="form-control" name="title" id="title" placeholder="Proposal title" value="<?=$voting->title?>">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="url" class="col-sm-2 form-control-label">Proposal URL</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" name="url" id="url" placeholder="Proposal URL" value="<?=$voting->url?>">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="name" class="col-sm-2 form-control-label">Description</label>
                            <div class="col-sm-10">
                                <textarea name="description" id="description" class="form-control" rows="4" placeholder="Optional"><?=$voting->description?></textarea>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="start_date" class="col-sm-2 form-control-label">Proposal start date (UTC+1)</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control datepicker" name="start_date" id="start_date" placeholder="Proposal start date" value="<?=($voting->start_date ? date("Y/m/d", $voting->start_date) : '')?>">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="end_date" class="col-sm-2 form-control-label">Proposal expiring date (UTC+1)</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control datepicker" name="end_date" id="end_date" placeholder="Proposal expiring date" value="<?=($voting->end_date ? date("Y/m/d", $voting->end_date) : '')?>">
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-lg-12 col-sm-12 col-xs-12 col-md-12 col-xl-6 m-t-sm-40">
                    <div class="card-box">
                        <h4 class="header-title m-t-0 m-b-30">Possible answers</h4>

                        <div class="answers">
                            <?php if(!$voting->id || !$answers){ ?>
                            <div class="form-group row">
                                <label class="col-sm-2 form-control-label">Answer</label>
                                <div class="col-sm-7">
                                    <input type="text" class="form-control" placeholder="Answer" name="answers[]" value="" <?=($votes ? 'readonly' : '')?> />
                                </div>
                                <div class="col-sm-3">
                                    <?php if(!$votes){ ?>
                                    <a href="javascript:void(0)" class="btn btn-danger deleteAnswer" title="Delete answer">
                                        <i class="fa fa-times"></i>
                                    </a>
                                    <?php } ?>
                                </div>
                            </div>
                            <?php }else{ ?>
                                <?php foreach ($answers as $anwser) { ?>
                                    <div class="form-group row">
                                        <label class="col-sm-2 form-control-label">Answer</label>
                                        <div class="col-sm-7">
                                            <input type="text" class="form-control" placeholder="Answer" name="answers[]" value="<?=$anwser->answer?>" <?=($votes ? 'readonly' : '')?> />
                                        </div>
                                        <div class="col-sm-3">
                                            <?php if(!$votes){ ?>
                                            <a href="javascript:void(0)" class="btn btn-danger deleteAnswer" title="Delete answer">
                                                <i class="fa fa-times"></i>
                                            </a>
                                            <?php } ?>
                                        </div>
                                    </div>
                                <?php } ?>
                            <?php } ?>
                        </div>

                        <?php if(!$votes){ ?>
                        <div class="form-group row">
                            <div class="col-sm-3">
                                <a href="javascript:void(0)" class="btn btn-success addAnswer" title="Add answer">
                                    <i class="fa fa-plus"></i>
                                </a>
                            </div>
                        </div>
                        <?php } ?>

                    </div>

                    <button type="submit" class="btn btn-primary">Save proposal</button>
                    <a href="/votings" class="btn btn-secondary">Back to overview</a>

                </div>
            </div>

        </div>
    </div><!-- end col-->

</form>

</div>
<!-- end row -->

<script>
    $(function(){
        $('.datepicker').datepicker({
            format: "yyyy/mm/dd"
        });

        $('.addAnswer').on('click', function(e){
            e.preventDefault();

            var $row = $('.answers').find('.row').first().clone();

            $row.find('input').val('');

            $('.answers').append($row);

            initButtons();
        });

        function initButtons(){
            $('.deleteAnswer').each(function(){
                var $btn = $(this);

                $btn.off('click').on('click', function(e){
                    e.preventDefault();

                    if($('.answers').find('.row').length > 1) {
                        $btn.closest('.row').remove();
                    }else{
                        $btn.closest('.row').find('input').val('');
                    }
                });
            });
        }
        initButtons();

        $('input[name="title"]').on('keyup', function(){
            var val = $(this).val();

            val = slugify(val);

            $('input[name="url"]').val(val);
        });

        function slugify(string) {
            const a = 'àáäâãåèéëêìíïîòóöôùúüûñçßÿœæŕśńṕẃǵǹḿǘẍźḧ·/_,:;'
            const b = 'aaaaaaeeeeiiiioooouuuuncsyoarsnpwgnmuxzh------'
            const p = new RegExp(a.split('').join('|'), 'g')

            return string.toString().toLowerCase()
                .replace(/\s+/g, '-')
                .replace(p, c => b.charAt(a.indexOf(c)))
                .replace(/&/g, '-and-')
                .replace(/[^\w\-]+/g, '')
                .replace(/\-\-+/g, '-')
                .replace(/^-+/, '')
                .replace(/-+$/, '')
        }
    })
</script>