
<div>
    <div class="row">
        <div class="col-sm-12">
            <div class="btn-group pull-right m-t-15">

                <button type="button" class="btn btn-custom dropdown-toggle waves-effect waves-light" data-toggle="dropdown" aria-expanded="false">Actions</button>

                <div class="dropdown-menu">
                    <a class="dropdown-item" href="/votings/edit">Add proposal</a>
                </div>

            </div>
            <!--<h4 class="page-title">Proposals</h4>-->
            <h4 class="page-title">&nbsp;</h4>
        </div>
    </div>

    <div class="row">

        <div class="col-xs-12 col-lg-12">
            <div class="card-box">

                <div class="table-responsive">
                    <table id="datatable" class="table table-striped table-bordered m-b-0">
                        <thead>
                        <tr>
                            <th>#</th>
                            <th>
                                Proposal
                            </th>
                            <th>Vote count</th>
                            <th>Votes confirmed</th>
                            <th>Starting date</th>
                            <th>Expiration</th>
                            <th></th>
                            <th>Second round</th>
                            <th>Results</th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php $c=0; foreach( $votings as $v ){ ?>
                            <tr>
                                <td><?=$votingsCount-$c?></td>
                                <td><?=$v->title?></td>
                                <td><?=$v->getVotes()->count()?></td>
                                <td><?=$v->getVotes('confirmed = 1')->count()?></td>
                                <td><?=($v->start_date ? date("Y/m/d H:i:s", $v->start_date) : '-')?></td>
                                <td><?=($v->end_date ? date("Y/m/d H:i:s", $v->end_date) : '-')?></td>
                                <td>
                                    <a href="/votings/edit/<?=$v->id?>" class="btn waves-effect waves-light btn-sm btn-warning" title="Edit proposal"> <i class="fa fa-wrench"></i> </a>
                                    <a href="/votings/votes/<?=$v->id?>" class="btn waves-effect waves-light btn-sm btn-success" title="View results"> <i class="fa fa-eye"></i> </a>
                                    <?php if($v->getVotes()->count() == 0){ ?>
                                    <a href="/votings/delete/<?=$v->id?>" onclick="return confirm('Are you sure?'); return false;" class="btn waves-effect waves-light btn-sm btn-danger" title="Delete voting"> <i class="fa fa-times"></i> </a>
                                    <?php } ?>
                                </td>
                                <td>
                                    <?php if(!$v->getSecondRound()){ ?>
                                        <a href="/votings/addSecond/<?=$v->id?>" class="btn waves-effect waves-light btn-sm btn-success" title="Create second proposal round" onclick="return confirm('Are you sure?'); return false;"> <i class="fa fa-plus"></i> </a>
                                    <?php } ?>
                                </td>
                                <td></td>
                            </tr>

                            <?php if($second = $v->getSecondRound()){ ?>
                                <tr>
                                    <td class="secondVotingRow"></td>
                                    <td class="secondVotingRow"><?=$second->title?></td>
                                    <td class="secondVotingRow noTextAlign"><?=$second->getVotes()->count()?></td>
                                    <td class="secondVotingRow noTextAlign"><?=$second->getVotes('confirmed = 1')->count()?></td>
                                    <td class="secondVotingRow noTextAlign"><?=($second->start_date ? date("Y/m/d H:i:s", $second->start_date) : '-')?></td>
                                    <td class="secondVotingRow noTextAlign"><?=($second->end_date ? date("Y/m/d H:i:s", $second->end_date) : '-')?></td>
                                    <td class="secondVotingRow noTextAlign">
                                        <a href="/votings/edit/<?=$second->id?>" class="btn waves-effect waves-light btn-sm btn-warning" title="Edit voting"> <i class="fa fa-wrench"></i> </a>
                                        <a href="/votings/votes/<?=$second->id?>" class="btn waves-effect waves-light btn-sm btn-success" title="View votes"> <i class="fa fa-eye"></i> </a>
                                        <?php if($second->getVotes()->count() == 0){ ?>
                                            <a href="/votings/delete/<?=$second->id?>" onclick="return confirm('Are you sure?'); return false;" class="btn waves-effect waves-light btn-sm btn-danger" title="Delete voting"> <i class="fa fa-times"></i> </a>
                                        <?php } ?>
                                    </td>
                                    <td class="secondVotingRow noTextAlign"></td>
                                    <td class="secondVotingRow noTextAlign"></td>
                                </tr>
                            <?php } ?>
                        <?php $c++;} ?>
                        </tbody>
                    </table>
                </div>

            </div>
        </div><!-- end col-->
    </div>
    <!-- end row -->
</div>