<?=date_default_timezone_set ( 'Europe/Amsterdam' );?>
<!doctype html>
<html>
    <head>
        <meta charset="utf-8">
        <style>
            @page{
                background-image: url("./files/pdf_background/voting_report.png");
                background-image-resize: 6;
                margin: 210px 30px 130px 65px;
            }
            body{
                font-family: gillsans;
                color: #FFF;
            }
        </style>
    </head>

    <body>

        <table style="width: 100%; padding-top: 100px;">
            <tr>
                <td style="text-align: center">
                    <h2><?=$voting->title?></h2>
                </td>
            </tr>
        </table>


        <table style="width: 100%; margin-top: 100px;">
            <?php foreach ($results as $answer => $votes){ ?>
                <tr>
                    <td style="text-align: center; font-size: 22px;">
                        <?=$answer?>
                    </td>
                    <td style="text-align: center; font-size: 22px;">
                        <?=number_format(($votes/$totalConfirmedVotes)*100, 0)?>%
                    </td>
                </tr>
            <?php } ?>
        </table>

        <table style="width: 100%; padding-top: 100px;">
            <tr>
                <td style="text-align: center">
                    <p>
                        Thank you all for voting! If you have any questions about the end result or the voting subject
                        itself, please feel free to join the
                        <a href="https://t.me/EUNOofficial" style="color: #FFF;" target="_blank">EUNO Telegram group </a>
                        and see them answered!<br /><br />

                        Kind regards,<br/>
                        EUNO team
                    </p>
                </td>
            </tr>
        </table>

    </body>
</html>