<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="A fully featured admin theme which can be used to build CRM, CMS, etc.">
    <meta name="author" content="Coderthemes">

    <!-- App Favicon -->
    <link rel="shortcut icon" href="assets/images/favicon.ico">

    <!-- App title -->
    <title>EUNO - Governance voting panel</title>

    <!-- App CSS -->
    <?=$this->assets->outputCss()?>

    <!-- HTML5 Shiv and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->

    <script src="assets/js/modernizr.min.js"></script>

</head>


<body>



<div class="account-pages"></div>
<div class="clearfix"></div>
<div class="wrapper-page">

    <div class="account-bg">
        <div class="card-box m-b-0">
            <div class="m-t-30 m-b-20">
                <form class="form-horizontal m-t-20" method="POST" action="/auth/start">

                    <div class="form-group ">
                        <div class="col-xs-12">
                            <?=$this->getContent()?>
                        </div>
                    </div>

                    <input type="hidden" name="<?php echo $this->security->getTokenKey()?>"
                           value="<?php echo $this->security->getToken()?>"/>

                    <div class="form-group ">
                        <div class="col-xs-12">
                            <input class="form-control" name="email" type="text" required="" placeholder="Username">
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-xs-12">
                            <input class="form-control" name="password" type="password" required="" placeholder="Password">
                        </div>
                    </div>

                    <div class="form-group text-center m-t-30">
                        <div class="col-xs-12">
                            <button class="btn btn-success btn-block waves-effect waves-light" type="submit">Login</button>
                        </div>
                    </div>


                </form>

            </div>
        </div>
    </div>
    <!-- end card-box-->
</div>
<!-- end wrapper page -->


<script>
    var resizefunc = [];
</script>

<?=$this->assets->outputJs()?>

</body>
</html>