
<div ng-app="crm" ng-controller="orderOverview">
    <div class="row">
        <div class="col-sm-12">
            <div class="btn-group pull-right m-t-15">

                <button type="button" class="btn btn-custom dropdown-toggle waves-effect waves-light" data-toggle="dropdown" aria-expanded="false">Actions</button>

                <div class="dropdown-menu">
                    <a class="dropdown-item" href="/index/addOrder">Add voting</a>
                </div>

            </div>
            <h4 class="page-title">Votings</h4>
        </div>
    </div>

    <div class="row">

        <div class="col-xs-12 col-lg-12">
            <div class="card-box">

                <div class="table-responsive">
                    <table id="datatable" class="table table-striped table-bordered m-b-0">
                        <thead>
                        <tr>
                            <th>
                                Voting
                            </th>
                            <th>Vote count</th>
                            <th>Votes confirmed</th>
                            <th>Voting added on</th>
                            <th>Voting expires</th>
                            <th></th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php foreach( $votings as $v ){ ?>
                            <tr>
                                <td><?=$v->title?></td>
                                <td><?=$v->getVotes()->count()?></td>
                                <td><?=$v->getVotes('confirmed = 1')->count()?></td>
                                <td><?=date("Y/m/d H:i:s", $v->add_date)?></td>
                                <td><?=date("Y/m/d H:i:s", $v->end_date)?></td>
                                <td>
                                    <a href="/index/edit/<?=$v->id?>" class="btn waves-effect waves-light btn-sm btn-warning" title="Edit voting"> <i class="fa fa-wrench"></i> </a>
                                    <a href="/index/votes/<?=$v->id?>" class="btn waves-effect waves-light btn-sm btn-success" title="View votes"> <i class="fa fa-eye"></i> </a>
                                    <?php if($v->getVotes()->count() == 0){ ?>
                                    <a href="/index/delete/<?=$v->id?>" onclick="return confirm('Are you sure?'); return false;" class="btn waves-effect waves-light btn-sm btn-danger" title="Delete voting"> <i class="fa fa-times"></i> </a>
                                    <?php } ?>
                                </td>
                            </tr>
                        <?php } ?>
                        </tbody>
                    </table>
                </div>

            </div>
        </div><!-- end col-->
    </div>
    <!-- end row -->
</div>

<script src="https://cdn.datatables.net/rowgroup/1.0.2/js/dataTables.rowGroup.min.js" type="application/javascript"></script>