<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Euno Governance Voting Portal - Thank you for voting</title>
        <meta name="author" content="@arrie1992">
        <link type="text/css" rel="stylesheet" href="/assets/css/vote_frontend.css" />
        <meta http-equiv="refresh" content="5; URL=/<?=$redirectUrl?>">
    </head>
    <body id="votingportal">
        <div class="votingSuccessModal">
            <img src="/assets/images/votingportal/vote-note-1.png" alt="Vote note" />
            <div class="blur"></div>
        </div>
    </body>
</html>