<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Euno Governance Room - Thank you for signing up</title>
        <meta name="author" content="@arrie1992">
        <link type="text/css" rel="stylesheet" href="/assets/frontend/css/style.css" />
    </head>
    <body id="votingportal">
        <div class="votingSuccessModal">
            <img src="/assets/images/signup/signup-note.png" alt="Vote note" />
            <div class="blur-signup"></div>
        </div>
    </body>
</html>