<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Euno Governance Room - Thank you for signing up</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="author" content="@arrie1992">
        <link type="text/css" rel="stylesheet" href="/assets/frontend/css/style.css?time=<?=time()?>" />
        <link type="text/css" rel="stylesheet" href="/assets/bootstrap/css/bootstrap.css" />
    </head>
    <body id="votingportal">
        <div class="votingSuccessModal">
            <div class="blur-signup"></div>
        </div>

        <div class="signup-note-modal">

            <div class="row">
                <div class="col-md-2 text-center hidden-xs">
                    <img src="/assets/images/signup/modal-logo.png" alt="Modal logo" />
                </div>
                <div class="col-md-8 text-center">
                    <h1>Thank you for signing up!</h1>

                    <p>
                        You are now egilible to participate in voting and joining our Telegram Governance Room.
                        You can contact any of our Core Members to get access to our Telegram Governance Room.
                        If you are not in our Official Telegram Channel, please check the link below:<br /><br />

                        <a href="https://t.me/EUNOofficial" target="_blank">https://t.me/EUNOofficial</a><br /><br />

                        Please note that once your masternode is offline, you will no longer have governance privileges.
                    </p>
                </div>
                <div class="col-md-2 text-center hidden-xs">
                    <img src="/assets/images/signup/modal-check.png" alt="Modal logo" />
                </div>
            </div>

        </div>
    </body>
</html>
